### ISSUE TITLE
npmfs.com is down

### ISSUE THREAD

**Issue by dy** [g-harel/npmfs#1]
Is that temporary @g-harel?
Such a useful tool that is!

**Comment by schfkt** [comment]
@dy in the meantime, you can run it locally with docker. Clone the repo and then:

```
docker build -t npmfs:latest .
docker run -p 8080:8080 npmfs:latest
```

**Comment by dy** [comment]
Just curious - would that be possible to run it fully from the frontend and host an app from github?

**Comment by dy** [comment]
I mean, that's not a big deal - there's also https://runpkg.com, which does the same, but not as nicely as npmfs.

**Comment by g-harel** [comment]
Hey @dy thanks for the heads up and sorry about the downtime!

It seems to be back running smoothly, do you remember what kind of error (`500`, `404`, etc.) you were getting? I'll try to dig up the logs.

It could have been an issue with the connection to the registry, or crawlers scraping `/compare` endpoints using up all the memory. I've [disallowed bots from accessing them](https://github.com/g-harel/npmfs/commit/9e02a4ae95f40c1714005e564b37d9e8cc79e6f9) to see if it helps.

There is nothing specifically stopping parts of the app from being implemented in the frontend, it's using public endpoints for the package tarballs and there are JS libraries to read their contents. However, it is currently implemented almost entirely as a backend application. The main benefit being _genuine™_ `git-diff-tree` results, but also cacheability and speed.

**Comment by dy** [comment]
It was just "Page not found" with google-like logo on it.

**Comment by andreineculau** [comment]
I'm getting internal server error on https://npmfs.com/package/@angular/compiler-cli/v/7.2.15

**Comment by g-harel** [comment]
@andreineculau 

It looks like the URL might have an extra `/v/` https://npmfs.com/package/@angular/compiler-cli/7.2.15/

**Comment by andreineculau** [comment]
@g-harel i didnt do anything else but follow instructions and replace j with f in a npmjs.com url

**Comment by g-harel** [comment]
Nice find, I'll add that url pattern to make sure the contract is respected.

I've opened an issue (#2) about this.
