### ISSUE TITLE
Download package link

### ISSUE THREAD

**Issue by zoxon** [g-harel/npmfs#3]
Thanks for npmfs, really missed this tool.
Can you add link to download package, please?

**Comment by g-harel** [comment]
I'm happy to hear you like it!

I've added a download link in the top-right of the page when in a package/version root.
_ex._ https://npmfs.com/package/express/4.17.1

**Comment by g-harel** [comment]
I thought it would be a great feature to have the download link for files/sub-directories too. The changes should be live now, thanks again for the suggestion!

https://npmfs.com/package/express/4.17.1/
https://npmfs.com/package/express/4.17.1/lib/router/
https://npmfs.com/package/express/4.17.1/lib/express.js
