### ISSUE TITLE
Chrome warning about possible domain name attack.

### ISSUE THREAD

**Issue by doowb** [g-harel/npmfs#6]
Hi, I just discovered this site and Chrome popped up this warning:

![image](https://user-images.githubusercontent.com/995160/106016032-0ece7a00-608d-11eb-8499-7016b36a082e.png)

I thought you may be interested in knowing this is happening. Also, if you know of a way to notify Chrome that this is a legit domain, I'd be interesting in how that's handled.

**Comment by g-harel** [comment]
Thanks for bringing this up, I'll look into it and report back!

**Comment by g-harel** [comment]
There seems to be an appeals process. There are some links at the bottom of [this page](https://support.google.com/chrome/answer/99020) with a little bit more info.

**Comment by g-harel** [comment]
I got the domain added to a list of exclusions, thanks for bringing this up!
