### ISSUE TITLE
File size

### ISSUE THREAD

**Issue by dy** [g-harel/npmfs#7]
Hi! That's very useful project thanks for doing that, used it so many times can't recount.
One suggestion - it would be very useful to have file size somewhere, to trace size change between versions.

**Comment by g-harel** [comment]
That's a great idea, I'll make it happen!

**Comment by g-harel** [comment]
## File size
![file](https://user-images.githubusercontent.com/9319710/115972670-66a64100-a515-11eb-9aef-231b371c924f.png)

## Diff change
![diff](https://user-images.githubusercontent.com/9319710/115972672-67d76e00-a515-11eb-9302-e659112d413c.png)
